# report.py

import requests
import textwrap

BASE_URL = "http://127.0.0.1:5000/api/v1/search"
QUERY    = "gymnastics"
MODES    = [
    "flat_clustering",
    "single_hac",
    "average_hac",
    "page_rank",
    "hits",
    "rocchio",
    "association_qe",
    "metric_qe",
    "scalar_qe",
]

def fetch(mode):
    r = requests.get(BASE_URL, params={"query": QUERY, "type": mode}, timeout=10)
    if r.status_code != 200:
        return {"error": f"HTTP {r.status_code}"}
    data = r.json()
    docs = data.get("query_results", [])
    sample = []
    for d in docs[:5]:
        sample.append({
            "url":         d.get("url",""),
            "cluster_num": d.get("cluster_num", None),
            "snippet":     (d.get("content","") or "")[:100].replace("\n"," ")
        })
    return {
        "echoed_query":   data.get("query", ""),
        "total_results":  len(docs),
        "sample_results": sample
    }

def main():
    print(f"# Search Engine Report for query: “{QUERY}”\n")
    for mode in MODES:
        info = fetch(mode)
        print(f"## Mode: `{mode}`")
        if "error" in info:
            print(f"**Error:** {info['error']}\n")
            continue

        print(f"- **Echoed query:** `{info['echoed_query']}`")
        print(f"- **Total results:** {info['total_results']}\n")
        print("### Sample Results")
        if not info["sample_results"]:
            print("_no results_\n")
            continue

        for i, doc in enumerate(info["sample_results"], 1):
            print(f"1. **URL:** {doc['url']}")
            if doc["cluster_num"] is not None:
                print(f"   - Cluster: {doc['cluster_num']}")
            print("   - Snippet:")
            for line in textwrap.wrap(doc["snippet"], width=80):
                print(f"     {line}")
            print()
    print("\n*Report generated by `python report.py`*")

if __name__ == "__main__":
    main()
